---

- name: Prepare Amazon Linux
  hosts: all
  become: true
  gather_facts: false
  tasks:
  # Docs: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
  - name: "Install python on Amazon Linux"
    yum:
      name: "python3"
      state: "present"
    when:
    - ansible_facts['distribution'] == 'Amazon'

  - name: "Install python on Ubuntu"
    apt:
      name: "python3"
      state: "present"
      update_cache: true
    when:
    - ansible_facts['distribution'] == 'Ubuntu'